import matplotlib.pyplot as plt


def generate_parameter_check_tex():
    with open('report_text.tex', 'a', encoding='utf-8') as f:
        f.write(r'\subsection{Wpływ rozmiaru populacji dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_population.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla populacji dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:population_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ populacji dla algorytmu BOA z lotem Levy’ego}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/boa_levy_population.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla populacji dla algorytmu BOA z lotem Levy’ego.}' + '\n')
        f.write(r'\label{fig:population_levy}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ liczby iteracji dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_iterations.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla liczby iteracji dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:iterations_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ liczby iteracji dla algorytmu BOA z lotem Levy’ego}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/boa_levy_iterations.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla liczby iteracji dla algorytmu BOA z lotem Levy’ego.}' + '\n')
        f.write(r'\label{fig:iterations_levy}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ wymiarów dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_dimensions.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla wymiarów dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:dimensions_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ wymiarów dla algorytmu BOA z lotem Levy’ego}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/boa_levy_dimensions.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla wymiarów dla algorytmu BOA z lotem Levy’ego.}' + '\n')
        f.write(r'\label{fig:dimensions_levy}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ parametru Maksymalnej częstotliwości dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_frequency.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla parametru Maksymalnej częstotliwości dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:frequency_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ parametru $\alpha$ dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_alpha.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla parametru $\alpha$ dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:alpha_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ parametru $\epsilon$ dla algorytmu nietoperza}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/bat_epsilon.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla parametru $\epsilon$ dla algorytmu nietoperza.}' + '\n')
        f.write(r'\label{fig:epsilon_bat}' + '\n')
        f.write(r'\end{figure}' + '\n')
        f.write('\n')
        f.write(r'\subsection{Wpływ parametru $\alpha$ dla algorytmu BOA z lotem Levy’ego}' + '\n\n')
        f.write(r'\begin{figure}[H]' + '\n')
        f.write(r'\centering' + '\n')
        f.write(r'\includegraphics[width=1\textwidth]{plots/boa_levy_alpha.png}' + '\n')
        f.write(r'\caption{Wynik eksperymentu dla parametru $\alpha$ dla algorytmu BOA z lotem Levy’ego.}' + '\n')
        f.write(r'\label{fig:alpha_levy}' + '\n')
        f.write(r'\end{figure}' + '\n')


def draw_plot_contains_parameter_to_best_score(tab_with_parameters, tab_with_best_score, parameter_name, title, label_name, file_name):
    plt.figure(figsize=(10, 6))
    plt.plot(tab_with_parameters, tab_with_best_score, label=label_name)
    plt.title(title)
    plt.xlabel(parameter_name)
    plt.ylabel('Best Value')
    plt.legend()
    plt.savefig(f'plots/{file_name}')


